# ConfigMap - Database initialization script
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-db-init
  labels:
    app: identity-access-service
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(36) PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        role VARCHAR(50) NOT NULL,
        password VARCHAR(255) NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS parents (
        user_id VARCHAR(36) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        room_number VARCHAR(20)
    );

    CREATE TABLE IF NOT EXISTS tokens (
        id SERIAL PRIMARY KEY,
        user_id VARCHAR(36) REFERENCES users(id) ON DELETE CASCADE,
        token_hash VARCHAR(64) NOT NULL UNIQUE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS token_blacklist (
        token_hash VARCHAR(64) PRIMARY KEY,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX idx_tokens_hash ON tokens(token_hash);
    CREATE INDEX idx_blacklist_hash ON token_blacklist(token_hash);
---
# PersistentVolumeClaim - Storage for database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-db-pvc
  labels:
    app: identity-access-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# Database Deployment - PostgreSQL database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-db
  labels:
    app: identity-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: identity-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-db-secret
                  key: password
            - name: POSTGRES_DB
              value: identity_db
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: identity-db-pvc
        - name: init-script
          configMap:
            name: identity-db-init
---
# Database Service - Internal Networking for PostgreSQL database
apiVersion: v1
kind: Service
metadata:
  name: identity-db
  labels:
    app: identity-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: identity-db