# Deployment identity-outbox-relay
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-outbox-relay
  labels:
    app: identity-outbox-relay
    component: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-outbox-relay
  template:
    metadata:
      labels:
        app: identity-outbox-relay
        component: relay
    spec:
      containers:
        - name: identity-outbox-relay
          image: identity-access-service:latest 
          command: ["./identity-relay"]       
          env:
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: identity-db-secret
                  key: connection-string
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: url
            - name: BABY_QUEUE_NAME
              value: "babies"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - "ps aux | grep identity-relay | grep -v grep"
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
